import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import { Container } from "./styled";


export default function Layout({ children }) {

  return (
    <Container>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <main>{children}</main>
{/*       <Footer /> */}
    </Container>
  );
}
